# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

C_num_leq_sorted <- function(a, b, tolerance) {
    .Call(`_uts_C_num_leq_sorted`, a, b, tolerance)
}

C_num_less_sorted <- function(a, b, tolerance) {
    .Call(`_uts_C_num_less_sorted`, a, b, tolerance)
}

C_sorted_union <- function(a, b, tolerance) {
    .Call(`_uts_C_sorted_union`, a, b, tolerance)
}

